name: Aptly

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
    - main

concurrency:
  group: >-
    ${{ github.event.inputs.head_ref || github.run_id }}


jobs:
  aptly:
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'envoyproxy'
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
    - run: |
        bazel build --config=ci //:aptly-config
        bazel run --config=ci @aptly config show -- -config "${PWD}/bazel-bin/.aptly" \
          | jq -r '.FileSystemPublishEndpoints.public.rootDir' \
          | grep /opt/build/repo/repository
