name: Build

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
    - main

concurrency:
  group: >-
    ${{ github.event.inputs.head_ref || github.run_id }}


jobs:
  build:
    runs-on: ubuntu-latest-8-cores
    if: ${{ false && github.repository_owner == 'envoyproxy' }}
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
    - run: |
        sudo mkdir /opt/build
        sudo chown runner:docker /opt/build
        ./build-repository.sh
        du -ch /opt/build
        du -ch ~/.cache
      env:
        CONTEXT: deploy-preview
        GITHUB_TOKEN: ${{ github.token }}
